name: 'nodenv/node-version'
description: 'Makes `nodenv local` available as a step output'
branding:
  icon: 'box'
  color: 'yellow'

inputs:
  nodenv-version:
    description: 'The version of nodenv to install'
    required: false
    default: '1.3.1'

outputs:
  node-version:
    description: 'The version of node as determined by nodenv'

runs:
  using: 'node12'
  main: 'dist/index.js'
